language: cpp
os: linux
dist: trusty
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - cmake-data
      - cmake
env:
  - GTEST_DIR="/usr/local/googletest/googletest-1.10.0"
before_install:
  - sudo git clone https://github.com/google/googletest
  - cd googletest
  - sudo git checkout release-1.10.0
  - sudo cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/googletest/googletest-1.10.0
  - sudo make
  - sudo make install
  - cd ..
script: 
  - make
  - make test
