language: cpp
os: linux
dist: trusty
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - cmake-data
      - cmake
env:
  - GTEST_DIR="/usr/local/googletest/googletest-1.8.0"
before_install:
  - sudo git clone https://github.com/google/googletest /usr/src
  - cd /usr/src/googletest && sudo git checkout release-1.8.0
  - cd /usr/src/googletest && sudo cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/googletest/googletest-1.8.0 && sudo make && sudo make install 
script: 
  - cd ~
  - make && make test
