language: cpp
os: linux
dist: trusty
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - cmake-data
      - cmake
      - libgtest-dev
script: make && make test
